FROM node:14-alpine AS builder
ADD . /vue
WORKDIR /vue
RUN mv -f src/views/login/index.vue.tensuns src/views/login/index.vue && \
    mv -f src/settings.js.tensuns src/settings.js && \
    npm install --registry=https://registry.npm.taobao.org && npm run build:prod

FROM nginx:stable-alpine
WORKDIR /www
COPY --from=builder /vue/http-ops.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /vue/dist dist/
