FROM arm64v8/python:3.10.9
ADD  sources.list /etc/apt
ADD . /flask
WORKDIR /flask
RUN  apt update -y && apt upgrade -y && apt install build-essential manpages-dev -y \
&& rm -rf /var/cache/apt/* \
&& pip3 install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple --no-cache-dir\
&& pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple --no-cache-dir
EXPOSE 2026
CMD ["python3","./manager.py"]
